# Generated by Django 4.0.2 on 2022-02-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangay',
            old_name='name',
            new_name='barangay',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='name',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='name',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region',
        ),
    ]
